# Generated by Django 5.0.1 on 2026-03-16 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('file_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('source_language', models.CharField(default='english', max_length=100)),
                ('target_language', models.CharField(default='english', max_length=100)),
                ('emotion_intensity', models.FloatField(default=1.5)),
                ('base_speed', models.FloatField(default=1.0)),
                ('total_chapters', models.IntegerField(default=0)),
                ('total_segments', models.IntegerField(default=0)),
                ('total_duration', models.FloatField(default=0.0)),
                ('generation_time', models.FloatField(default=0.0)),
                ('output_audio_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audiobooks/chapters/')),
                ('duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='audiobooks.book')),
            ],
            options={
                'ordering': ['book', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('voice_id', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('emotion', models.CharField(default='neutral', max_length=50)),
                ('segment_type', models.CharField(choices=[('dialogue', 'Dialogue'), ('narration', 'Narration')], default='narration', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audiobooks/segments/')),
                ('duration', models.FloatField(default=0.0)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audiobooks.chapter')),
            ],
            options={
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('voice_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], max_length=10)),
                ('language', models.CharField(default='english', max_length=100)),
                ('sample_audio', models.FileField(upload_to='voices/samples/')),
                ('embedding_file', models.FileField(blank=True, null=True, upload_to='voices/embeddings/')),
                ('is_custom', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', '-created_at'], name='audiobooks__user_id_18284c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='audiobooks__status_58e8af_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['file_id'], name='audiobooks__file_id_4dce86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'chapter_number')},
        ),
    ]
